micronaut:
  application:
    name: micronautBasic
endpoints:
  prometheus:
    sensitive: true
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
---
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: microservices
    password: passpass
    schema-generate: NONE
    dialect: mysql
    connection-timeout: 1500
    max-lifetime: 1500

flyway:
  enabled: false
  datasources:
    default:
      enabled: false

