micronaut:
  application:
    name: micronautBasic
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          refresh-token:
            secret: pleaseChangeThisSecretForANewOne
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne

datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: microservices
    password: passpass
    schema-generate: NONE
    dialect: mysql
    connection-timeout: 1500
    max-lifetime: 1500

flyway:
  enabled: false
  datasources:
    default:
      enabled: false

